---
- name: "Delete DB using AWS CLI"
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    instance_id: wordpressdbclixx-ecs
    region: us-east-1

  tasks:
    - name: Delete RDS instance without final snapshot using AWS CLI
      shell: |
        aws rds delete-db-instance \
          --db-instance-identifier "{{ instance_id }}" \
          --skip-final-snapshot \
          --region "{{ region }}"
      register: delete_db_result
      ignore_errors: true

    - name: "Verify deletion command success"
      debug:
        msg: "Deletion initiated with result: {{ delete_db_result.stdout }}"
      when: delete_db_result is defined and delete_db_result.stdout != ""

    - name: Wait for the RDS instance to be deleted
      retries: 20              # Increase retries if deletion takes longer
      delay: 90                # Increase delay between checks
      shell: |
        aws rds describe-db-instances \
          --db-instance-identifier "{{ instance_id }}" \
          --region "{{ region }}" \
          --query 'DBInstances[0].DBInstanceStatus' \
          --output text 2>/dev/null || echo "DBInstanceNotFound"
      register: db_status
      until: db_status.stdout == "DBInstanceNotFound"
      ignore_errors: true

    - debug:
        msg: "Database instance {{ instance_id }} deletion result: {{ delete_db_result }}"






# ---
#   - name: "Delete DB"
#     hosts: localhost
#     connection: local
#     vars:
#       instance_id: wordpressdbclixxjenkins
#     tasks:

#       - name: remove a db instance without taking a final snapshot
#         rds_instance:
#             id: "{{ instance_id }}"
#             state: absent
#             skip_final_snapshot: True
#             region: us-east-1