---
- name: "Delete DB using AWS CLI"
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    instance_id: wordpressdbclixx-ecs
    region: us-east-1

  tasks:
    - name: Delete RDS instance without final snapshot using AWS CLI
      shell: |
        aws rds delete-db-instance \
          --db-instance-identifier "{{ instance_id }}" \
          --skip-final-snapshot \
          --region "{{ region }}"
      environment:
        AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        AWS_DEFAULT_REGION: "{{ lookup('env', 'AWS_DEFAULT_REGION') | default(region) }}"
      register: delete_db_result
      ignore_errors: true

    - name: Verify deletion command success
      debug:
        msg: "Deletion initiated with result: {{ delete_db_result.stdout }}"
      when: delete_db_result is defined and delete_db_result.stdout != ""

    - name: Wait for the RDS instance to be deleted
      retries: 30  # Increase retries to handle long deletion times
      delay: 120   # Wait 120s between retries to avoid AWS API throttling
      shell: |
        aws rds describe-db-instances \
          --db-instance-identifier "{{ instance_id }}" \
          --region "{{ region }}" \
          --query 'DBInstances[0].DBInstanceStatus' \
          --output text 2>/dev/null || echo "DBInstanceNotFound"
      environment:
        AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        AWS_DEFAULT_REGION: "{{ lookup('env', 'AWS_DEFAULT_REGION') | default(region) }}"
      register: db_status
      until: db_status.stdout == "DBInstanceNotFound"
      ignore_errors: true

    - name: Confirm database deletion
      debug:
        msg: "Database instance {{ instance_id }} deletion result: {{ delete_db_result }}"
